language: php
php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql


install:
  - sh -c "if [ '$DB' = 'mariadb' ]; then travis/setup-mariadb.sh; fi"
  - sh -c "if [ `php -r "echo (int) version_compare(PHP_VERSION, '5.3.19', '>=');"` = "1" ]; then travis/setup-webserver.sh; fi"
  - travis/install-php-extensions.sh
  - cd cybyd
  - php ../composer.phar install --dev --no-interaction --prefer-source
  - cd ..

before_script:
  - sh -c "if [ '$DB' = 'mysql' -o '$DB' = 'mariadb' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS cybyd;'; fi"

script:
  - cd build
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' -a '$DB' = 'mysql' ]; then ../phpBB/vendor/bin/phing sniff; fi"
  - cd ..
  - phpBB/vendor/bin/phpunit --configuration travis/phpunit-$DB-travis.xml
  
notifications:
  email:
    recipients:
      - twitter@xdns.ro
    on_success: change
    on_failure: change

matrix:
  allow_failures:
    - php: hhvm
